export * from './user/create.dto'
export * from './user/login.dto'
export * from './user/refreshToken.dto'
export * from './user/generateChangePassword.dto'
export * from './user/changePassword.dto'

export * from './university/list.dto'
export * from './university/getById.dto'
export * from './university/create.dto'
export * from './university/update.dto'
export * from './university/delete.dto'
